### ISSUE TITLE
Potential open in editor bug

### ISSUE THREAD

**Issue by orschiro** [SergKolo/indicator-bulletin#3]
I cannot remove the second line. Edited in Atom editor.

![open in editor](https://cloud.githubusercontent.com/assets/170947/24693777/87bb5652-19df-11e7-941e-bb52f1367dff.gif)

**Comment by orschiro** [comment]
Actually, I cannot edit and save items in Atom editor. 

Atom freezes.

Can you confirm the problem, @SergKolo?

**Comment by SergKolo** [comment]
@orschiro  Hi, Robert ! I've Atom on my system as well and it opens and edits just fine.   It could be atom's issue.

**Comment by orschiro** [comment]
Thank you for testing it!

So, let me try a different editor then. 

How could I temporarily "open in editor" with a different editor?

**Comment by SergKolo** [comment]
@orschiro  Hi, Robert ! Sorry for late response. Currently busy with university stuff, so had to deprioritize working on software and Ask Ubuntu. Changing text editor temporarily can be done via ~/.local/share/applications/mimeapps.list file, and adding `text/plain=atom.desktop`. Here's example from my file

[Added Associations]
application/vnd.openxmlformats-officedocument.wordprocessingml.document=abiword.desktop;
application/pdf=xpdf.desktop;
application/x-java=runJava.desktop;

[Default Applications]
text/plain=atom.desktop
application/pdf=xpdf.desktop
application/x-java=runJava.desktop
text/x-arduino=arduino-arduinoide.desktop
text/html=firefox
x-scheme-handler/tg=telegramdesktop.desktop

**Comment by orschiro** [comment]
Thank you, @SergKolo!

The issue is actually no longer occurring. 

I will close this. Probably it was a user error on my side and not related to your software.
