### ISSUE TITLE
Can I use this in Linux Mint?

### ISSUE THREAD

**Issue by rafaeldelucena** [SergKolo/indicator-bulletin#6]
Mint uses Cinnamon, this indicator can be used there?

Thanks!

**Comment by SergKolo** [comment]
@rafaeldelucena  Hi ! I've tested the indicator on Cinnamon 3.6.7 and it works alright. The indicator can work on desktop environments that  support App Indicators, Gtk, and generally GNOME-based, so yes it can work in Mint or just any other OS with Cinnamon. I've also commited a bug fix, so if you're planning to install via PPA and apt-get, please wait at least 24 hours for the update to propagate into the PPA from github.  Instructions on how to install from PPA are in the README.md file
